- Gemfile
- Gemfile.lock
- app/controllers/admin_controller.rb
- app/controllers/application_controller.rb
- app/controllers/user_controller.rb
- app/helpers/user_helper.rb
- app/models/ability.rb
- app/views/admin/index.html.erb
- app/views/user/_form.html.erb
- app/views/user/edit.html.erb
- app/views/user/new.html.erb
- config/routes.rb
This addresses issue #5.
I've reworked the code to better use devise and added cancan (actually cancancan!) to handle authorisation. Edit forms now allow an admin to change role of user. Admin dashboard supports delete.
The existing tests covered the basic functionality to authorise user to see dashboard and list of users. Haven't added anything new at this point as then I'd be testing devise/cancan
> Reworked to use cancan based authorisation

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/organisations.scss
- app/controllers/application_controller.rb
- app/controllers/organisations_controller.rb
- app/controllers/registrations_controller.rb
- app/helpers/organisations_helper.rb
- app/models/organisation.rb
- app/models/user.rb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
- db/migrate/20150306133403_add_organisation_id_to_users.rb
- db/schema.rb
- features/signup.feature
- features/step_definitions/register_steps.rb
- features/step_definitions/web_steps.rb
- spec/controllers/organisations_controller_spec.rb
- spec/controllers/registrations_controller_spec.rb
- spec/factories/organisations.rb
- spec/helpers/organisations_helper_spec.rb
- spec/models/user_spec.rb
Allows users to associate themselves with an organisation on sign up and to change it from their profile. Only one user can be associated with chosen organisation and users can create an organisation for themselves if it does not already exist.
> Organisation signup

- .gitignore
- Gemfile
- Gemfile.lock
- config/environments/development.rb
- config/environments/production.rb
- config/initializers/devise.rb
> Configured mandrill in action mailer, added dotenv to read environment in dev

- lib/tasks/organisations.rake
> Add rake task to be called by heroku scheduler

- app/controllers/assessments_controller.rb
- app/models/assessment.rb
- app/models/questionnaire.rb
- app/models/score.rb
- app/views/assessments/_overview.html.erb
- app/views/assessments/index.html.erb
- app/views/assessments/report.html.erb
- app/views/assessments/show.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20150318112628_create_scores.rb
- db/schema.rb
- features/assessments.feature
- features/step_definitions/assessment_steps.rb
- lib/assessment_scorer.rb
- lib/progress_calculator.rb
- spec/factories/scores.rb
- spec/lib/progress_calculator_spec.rb
- spec/models/assessment_spec.rb
- spec/models/score_spec.rb
Implementation of #8 and #66 
* Marking an assessment as complete will update its state and record maturity scores in the `Score` model
* Fixed start date not being set when new assessment is created
* Allow user to mark assessment as completed when all activities have been assessed
* Allow user to navigate to a report page for a completed assessment (report page itself only a stub currently)
> Save scores

- app/models/assessment_answer.rb
- spec/factories/assessment_answers.rb
- spec/models/assessment_answer_spec.rb
> adds test and logic for removing invalidated answers

- app/controllers/application_controller.rb
- app/controllers/user_controller.rb
- app/models/user.rb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/user/_form.html.erb
- db/migrate/20150320160725_add_name_to_users.rb
- db/schema.rb
- features/signup.feature
- spec/factories/user.rb
Addresses #85 - Adds a name field to the user
> User's name

- app/controllers/assessment_answers_controller.rb
- app/models/assessment_answer.rb
- app/models/question.rb
- app/views/assessment_answers/_form.html.erb
- app/views/assessment_answers/edit.html.erb
- app/views/assessment_answers/new.html.erb
- app/views/assessments/show.html.erb
- features/questions.feature
- spec/models/question_spec.rb
> Navigation

- app/views/assessments/_assessment_summary.html.erb
- app/views/assessments/_first_assessment.html.erb
- app/views/assessments/index.html.erb
- features/assessments.feature
Tidy up the list of assessments page. Still needs proper styling though.
> Tidy list of assessments

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/my_assessments.scss
- app/assets/stylesheets/question.scss
- app/assets/stylesheets/report.scss
- app/helpers/application_helper.rb
- app/views/assessment_answers/_form.html.erb
- app/views/assessment_answers/edit.html.erb
- app/views/assessment_answers/new.html.erb
- app/views/assessments/_assessment_summary.html.erb
- app/views/assessments/index.html.erb
- features/assessments.feature
- features/questions.feature
Addresses #99 adds initial styling to the my assessment and question pages.
There's a few areas still to improve but I'll add those as separate issues.
> Assessment styling

- app/controllers/registrations_controller.rb
- app/models/user.rb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/layouts/_header.html.erb
- config/locales/en.yml
- features/home.feature
- features/signup.feature
- features/step_definitions/authentication_steps.rb
- features/step_definitions/web_steps.rb
Addresses #103, #106, #107, #108, #109
> Sign in and registration tidy

- app/views/assessments/_overview.html.erb
> adds link to first answer if activity is complete

- app/controllers/application_controller.rb
- features/signup.feature
> Redirect to my assessments after signin

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_password.html.erb
- config/locales/en.yml
Addresses #100 and #112.
Add form validator plugin to the project and attributes on the relevant forms.
> Added some client-side validation to registration and sign-in pages

- app/assets/stylesheets/targets.scss
- app/views/assessments/index.html.erb
- app/views/targets/edit.html.erb
- features/targets.feature
> Style targets

- app/controllers/assessment_answers_controller.rb
- features/questions.feature
- features/step_definitions/question_steps.rb
#126 - redirects user to next question where possible on update
> Revise activity

- app/assets/stylesheets/application.scss
- app/helpers/application_helper.rb
- app/views/assessment_answers/edit.html.erb
- app/views/assessment_answers/new.html.erb
- app/views/assessments/edit.html.erb
- app/views/assessments/report.html.erb
- app/views/assessments/show.html.erb
- features/assessments.feature
#119 adds breadcrumbs to assessment, assessment editing, questions, and report pages 
Are there any other pages that need a breadcrumb?
> Breadcrumbs

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/buttons.scss
- app/assets/stylesheets/home.scss
- app/helpers/application_helper.rb
- app/views/assessment_answers/edit.html.erb
- app/views/assessment_answers/new.html.erb
- app/views/assessments/_assessment_summary.html.erb
- app/views/assessments/_first_assessment.html.erb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/home/index.html.erb
- app/views/links/_link_fields.html.erb
- app/views/pages/about.html.erb
- app/views/pages/cookie_policy.html.erb
- app/views/pages/privacy_policy.html.erb
- config/initializers/devise.rb
- config/routes.rb
* Home page
* About pages from #34 
* Fix up button styles across the application
* Fix up app config to use the right email address
> About page content

- db/seeds.rb
For #127. Will add an admin account when `db:seed` is run. email and password are configured in heroku already.
> Add default admin

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/basic.scss
- app/assets/stylesheets/my_assessments.scss
- app/helpers/assessments_helper.rb
- app/models/dimension.rb
- app/views/assessments/_overview.html.erb
- app/views/assessments/show.html.erb
#121  restyles the assessment page
> Assessment style

- app/assets/stylesheets/home.scss
- app/views/home/index.html.erb
#141 - fixes header and button colours
> fix home page styles

- app/helpers/application_helper.rb
> changes link to report if assessment is complete in breadcrumb link

- app/assets/stylesheets/basic.scss
- app/assets/stylesheets/home.scss
Addresses #141 - use white text for coloured header buttons
> Header styles

- app/views/devise/sessions/new.html.erb
- app/views/home/index.html.erb
> adds user feedback link

- app/views/pages/about.html.erb
> Add funding note

- app/controllers/assessment_answers_controller.rb
> makes sure to advance to next question when a no updated to a yes

- app/views/devise/mailer/reset_password_instructions.html.erb
> Change password reset email text

- app/assets/stylesheets/question.scss
- app/views/assessment_answers/_form.html.erb
- app/views/links/_link_fields.html.erb
> Respaces and styles add link fields

- app/models/assessment_answer.rb
> Fixes navigation bug: back to previous question rather than first

- app/views/assessments/show.html.erb
- app/views/pages/about.html.erb
Update links to maturity model to reflect new URL.
Same for PDF download of doc.
> Fix links to maturity model and docs

- app/views/assessments/_first_assessment.html.erb
> Comment out download link

- app/views/assessments/_overview.html.erb
- app/views/assessments/show.html.erb
- features/assessments.feature
- features/questions.feature
> Rename dimension to theme. Make edit links into buttons

- app/views/statistics/_organisations_tab.html.erb
- app/views/statistics/data.html.erb
- app/views/statistics/index.html.erb
- features/statistics.feature
- features/step_definitions/web_steps.rb
> Minor text/formatting changes on heatmap page

- app/helpers/application_helper.rb
- app/views/assessment_answers/edit.html.erb
- app/views/assessment_answers/new.html.erb
- app/views/assessments/edit.html.erb
- app/views/assessments/report.html.erb
- app/views/assessments/show.html.erb
- app/views/layouts/application.html.erb
- features/assessments.feature
- features/home.feature
- features/step_definitions/web_steps.rb
> Create separate block for breadcrumb to fix page titles

- app/models/assessment_answer.rb
- spec/models/assessment_answer_spec.rb
> Touch assessment when questions are answered

- app/assets/javascripts/application.js
- app/views/assessments/_activity_label.html.erb
- app/views/assessments/_detail_tab.html.erb
- app/views/assessments/_improvements_tab.html.erb
- app/views/assessments/_next_goal_label.html.erb
- app/views/assessments/_overview.html.erb
- app/views/assessments/_score_label.html.erb
- app/views/assessments/_theme_label.html.erb
- app/views/statistics/_organisations_tab.html.erb
- config/locales/en.yml
> Ensure tooltips are working, add new tips to assessment overview.

- app/controllers/assessment_answers_controller.rb
- app/views/assessments/show.html.erb
- features/assessments.feature
- features/questions.feature
Addresses #209 and #207. Also fixes button style from #174
> Additional confirmations

- app/views/assessments/_improvements_tab.html.erb
Ensure improvements are ordered by id
> Order improvements

- app/assets/stylesheets/heatmap.scss
- app/helpers/statistics_helper.rb
- app/models/organisation.rb
- app/models/user.rb
- app/views/statistics/_organisations_tab.html.erb
- app/views/statistics/index.html.erb
- features/statistics.feature
- lib/organisation_scorer.rb
* #253 
* #226 -- some suggested wording changes
* #20
> Heatmap comparison

- app/controllers/statistics_controller.rb
- app/helpers/statistics_helper.rb
- app/models/organisation.rb
- app/models/organisation_score.rb
- app/views/statistics/index.html.erb
- db/migrate/20150506111100_create_organisation_scores.rb
- db/schema.rb
- features/statistics.feature
- features/step_definitions/statistics_steps.rb
- lib/organisation_scorer.rb
- lib/statistics_generator.rb
- lib/tasks/statistics.rake
- spec/controllers/statistics_controller_spec.rb
- spec/factories/organisation_scores.rb
- spec/lib/statistics_generator_spec.rb
> Switch statistics page to use results of a background task

- .travis.yml
- app/controllers/statistics_controller.rb
- app/helpers/statistics_helper.rb
- app/views/statistics/_organisations_tab.html.erb
- config/application.rb
Add env variable for configuring display of heatmap
> Conditional heatmap

- app/views/home/index.html.erb
- app/views/layouts/_footer.html.erb
- app/views/layouts/_header.html.erb
- app/views/pages/contact.html.erb
- config/routes.rb
- features/home.feature
Add new text to the homepage
Add Feedback and Get in touch link to new contact page
> Revise homepage; add contact page

- app/assets/stylesheets/my_assessments.scss
- app/views/assessments/index.html.erb
- app/views/assessments/report.html.erb
Style the goal button on the my assessment page
Add a link to set goals from the report
> Goal button

- app/assets/stylesheets/my_assessments.scss
- app/views/assessment_answers/_form.html.erb
- app/views/assessments/_improvements_tab.html.erb
- app/views/assessments/show.html.erb
Incorporate some suggestions made by JeniT
> Post review tweaks

- app/controllers/admin_controller.rb
- app/controllers/user_controller.rb
- app/views/admin/index.html.erb
> Admin page tweaks

- app/helpers/devise_helper.rb
- features/signup.feature
> Change header for default devise error messages

- app/views/assessments/show.html.erb
- features/assessments.feature
> Changed button label, added warning

- app/views/assessments/_overview.html.erb
- lib/organisation_scorer.rb
> Post deployment bug fixes

- README.md
- survey/README.md
@Floppy @pezholio @pkqk @pikesley have added some initial documentation ahead of our handover meeting later.
> Added initial documentation for handover

- app/controllers/assessments_controller.rb
- app/views/assessments/_activity_tab.html.erb
- app/views/assessments/_summary_tab.html.erb
- features/report.feature
- features/sharing.feature
- features/step_definitions/assessment_steps.rb
- lib/tasks/organisations.rake
> Allow shared summary data download

- app/views/devise/registrations/edit.html.erb
- features/signup.feature
- features/step_definitions/authentication_steps.rb
- lib/tasks/organisations.rake
> Fix password changing

- app/views/statistics/data.html.erb
> Add certificate badge

- .gitignore
- app/views/statistics/_organisations_tab.html.erb
- features/statistics.feature
to fix #308 on a surface level - per @Stephen-Gates remarks here https://github.com/theodi/pathway/issues/308#issuecomment-297159348 some deeper changes to  the name of variables in `score_organisations` (23, organisation_scorer.rb) might be advisable in a subsequent fix
> Assessments from registered users

- app/views/layouts/_footer.html.erb
update email address so that Labs handles any user queries arising from interactions on main webpage
> Change email from info@ to labs@

- README.md
prior title was to ODMAT acronym, amended to Open Data Pathway, ODMAT acronym included within copy
> updating title

- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
inclusion of all required MD github files for contributing
> Community contributions documentation

- app/assets/javascripts/forms.js.erb
- app/views/assessments/show.html.erb
This PR fixes #
Changes proposed in this pull request:
-
-
-
> Fix Jquery interation by returing false in obeserve_toggles function
